technologies = ["Python"]
categories = ["Correctness", "Quality", "Testing", "Security"]
exclude = ["*.md", "poetry.lock", "eval/classified_articles.py"]
model = "gpt-4.1"
silent = false
publish = true
