[default]
model = 'gpt-4.1'
score_threshold = 8
prompt = 'development'

service_desk_project_key=18
service_desk_request_id_type=230

[eval]
model = 'gpt-4.1'
score_threshold = 8
prompt = 'development'
samples = 3

[prompts]
development = """
I'm in software development. I develop web applications and mobile applications.
Given a text with cybersecurity news,
Give a score 1-10 to each one of all the articles, depending on how relevant they are to me. Give me back the articles with the relevance that you think they have.
The criteria to follow is:
- I develop with Python, javascript, AWS, android and ios. Also show vulnerabilities about other cloud providers that are directly related with development.
- I'm not interested in libraries vulnerabilities when they are impersonating a legit library, consider them as malware. I'm interested in vulnerabilities of legit libraries when they are critical.
- Even if it's a vulnerability related with development but does not belong to the techonolgies that I'm interested in, it is not relevant for me.
- I'm not interested in malware related news, nor malware campaigns or hackers exploiting vulnerabilities or rootkits using already known vulnerabilities. I'm interested only in newly discovered vulnerabilities.
- I'm only interested in the following mobile brands when it comes to hardware mobile vulnerabilities: Google, Apple, Samsung, Oppo, Motorola, OnePlus, Sony, Lenovo, OPPO, Huawei, Oneplus, Acer, Asus, Nokia, LG, HTC
- I deploy using docker containers, with linux images.
- I'm interested in browsers vulnerabilities.
- I usually use postgresql as a DB, but I'm also interested on other major DB vendors that are commonly used along with the technologies I've mentioned.

very important:
- Make a distinction between exploits and vulnerabilities being exploited and newly discovered vulnerabilities.
- Articles not related to the technologies I use are not relevant for me.
"""