# Project information
site_name: Py Package
site_author: Elements
site_description: >-
  The greatest project ever created.
# Repo info
repo_url: https://gitlab.com/makerstreet-development/elements/backend/lightman_ai

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Configuration
theme:
  name: material
  language: en

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  icon:
    repo: fontawesome/brands/gitlab

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Page tree
nav:
  - Home:
      - Intro: index.md
      - Developers Guide:
          - Getting Started: developers-guide/getting-started.md

plugins:
  - search
