# This workflow will check our code for having a proper format, as well as the commit message to meet the expected ones

name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install --with test,lint

      - name: Lint
        run: |
          poetry run ruff format --check src tests eval
          poetry run ruff check src tests eval 
          poetry run mypy src tests eval

  lint-commit:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    name: "Lint commit message"
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          python -m pip install commitizen
      - name: Check commit message
        run: cz check --rev-range HEAD
